spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DATABASE:event_booking}}
spring.datasource.username=${POSTGRES_USER:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${POSTGRES_PASSWORD:${DB_PASSWORD:postgres}}

jwt.secret=${JWT_SECRET:my-very-long-secret-password-key-32chars}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.forward-headers-strategy=framework
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}